vla_path: openvla/openvla-7b
data_root_dir: /mnt/HDD-6940GB/Dataset/LIBERO-datasets-multiview
benchmark_name: libero_spatial
camera_view: agentview_rgb
run_root_dir: /home/szliutong/Projects/openvla/vla-scripts/finetune_libero/agentview_rgb/runs
adapter_tmp_dir: /home/szliutong/Projects/openvla/vla-scripts/finetune_libero/agentview_rgb/adapters
batch_size: 8
max_steps: 50000
save_steps: 5000
log_every_n_steps: 10
learning_rate: 0.0005
grad_accumulation_steps: 2
image_aug: true
rotate_image_180: true
num_workers: 4
random_seed: 7
save_latest_checkpoint_only: true
use_lora: true
lora_rank: 32
lora_dropout: 0.0
use_quantization: false
use_wandb: false
wandb_project: openvla
wandb_entity: stanford-voltron
run_id_note: null
